name: Release
on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        options: [patch, minor, major, custom]
        default: patch
      custom_version:
        required: false
jobs:
  release:
    permissions:
      contents: write
    uses: openmrs/openmrs-contrib-gha-workflows/.github/workflows/release-frontend-module.yml@frontend-tagged-release
    with:
      release_type: ${{ inputs.release_type }}
      release_version: ${{ inputs.custom_version }}
      release_publish_command: 'yarn pack'   # stands in for npm publish
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      BOT_PAT: ${{ secrets.OMRS_BOT_GH_TOKEN }}
